### ISSUE TITLE
Missing `ICoreWebView2CompositionController3`

### ISSUE THREAD

**Issue by amrbashir** [wravery/webview2-rs#11]
Seems like [`ICoreWebView2CompositionController3`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2compositioncontroller3?view=webview2-1.0.1369-prerelease) is not generated which is used to forward drag/drop from an IDropTarget.

**Comment by amrbashir** [comment]
Sorry for the noise, I didn't see that the interface is not stable yet.

**Comment by wravery** [comment]
OK, np. I try to keep up with new releases of the SDK, but I may fall behind if I don't notice the release notification. If you think something is missing, feel free to open another issue.

**Comment by amrbashir** [comment]
Looks like there is a new release that includes this interface https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10137028

**Comment by wravery** [comment]
Just published 0.20.0 of `webview2-com-sys` and `webview2-com` to crates.io with the updated SDK. I verified that it included this interface.

I kept `windows-rs` 0.39.0 for this version, so it doesn't depend on updating that at the same time. I'll publish 0.21.0 in a little bit once I've done the `windows-rs` upgrade to 0.43.0.

**Comment by amrbashir** [comment]
Wow that was fast, thanks.
