### ISSUE TITLE
Update the sdk

### ISSUE THREAD

**Issue by IllusionPerdu** [wravery/webview2-rs#14]
Hello,

Can you update to the last release : 1.0.1518.46

And if it's possible make a branch with the prerelease 1.0.1619-prerelease because i think the "The Custom Scheme Registration API" is interesting ;)

Or if you don't have the time can you explain how to update.

**Comment by wravery** [comment]
I just published an update with 1.0.1518.46 to crates.io, it's version 0.22.0. I'll have to think about the best way to create a prerelease branch, it would need at least a separate winmd file generated from the prerelease SDK headers/libs.

**Comment by wravery** [comment]
The main branch is currently at `1.0.1774.30`, so the initial reason for this issue should be addressed.
