### ISSUE TITLE
GitLab CI windows / webview2-com-sys: failed to run custom build command

### ISSUE THREAD

**Issue by muja** [wravery/webview2-rs#23]
Running the build for webview2-com-sys fails on GitLab CI fails with the error `Io(Error { kind: NotFound, message: "program not found" } )`. Unfortunately it doesn't say which program was not found. There also seems to not be a list of build dependencies in the README.

The minimal reproducible .gitlab-ci.yml is this: 

```yaml
stages:
  - build

build-job:
  stage: build
  image: rust
  tags:
  - shared-windows
  - windows
  - windows-1809
  script:
    - choco install -y rust
    - cargo new foo
    - cd foo
    - cargo add webview2-com-sys
    - cargo build
```

This is the full output:

```
   Compiling webview2-com-sys v0.26.0
error: failed to run custom build command for `webview2-com-sys v0.26.0`
Caused by:
  process didn't exit successfully: `C:\GitLab-Runner\builds\danyel\sky-fi\blabla\target\debug\build\webview2-com-sys-d3e6eca53f705af0\build-script-build` (exit code: 1)
  --- stdout
  cargo:rustc-link-search=native=C:\GitLab-Runner\builds\danyel\sky-fi\blabla\target\debug\build\webview2-com-sys-99dd0865e5d8b1a6\out\Microsoft.Web.WebView2.1.0.1938.49\build\native\x64
    Finished writing `C:\GitLab-Runner\builds\danyel\sky-fi\blabla\target\debug\build\webview2-com-sys-99dd0865e5d8b1a6\out\Microsoft.rs` in 1.95s
  --- stderr
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\arm64\\WebView2Loader.dll" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\arm64\\WebView2Loader.dll"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\arm64\\WebView2Loader.dll.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\arm64\\WebView2Loader.dll.lib"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\arm64\\WebView2LoaderStatic.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\arm64\\WebView2LoaderStatic.lib"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x64\\WebView2Loader.dll" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x64\\WebView2Loader.dll"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x64\\WebView2Loader.dll.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x64\\WebView2Loader.dll.lib"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x64\\WebView2LoaderStatic.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x64\\WebView2LoaderStatic.lib"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x86\\WebView2Loader.dll" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x86\\WebView2Loader.dll"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x86\\WebView2Loader.dll.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x86\\WebView2Loader.dll.lib"
  Copy from "C:\\GitLab-Runner\\builds\\danyel\\sky-fi\\blabla\\target\\debug\\build\\webview2-com-sys-99dd0865e5d8b1a6\\out\\Microsoft.Web.WebView2.1.0.1938.49\\build\\native\\x86\\WebView2LoaderStatic.lib" -> "C:\\Users\\gitlab_runner\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\webview2-com-sys-0.26.0\\x86\\WebView2LoaderStatic.lib"
  Error: Io(Error { kind: NotFound, message: "program not found" })
Cleaning up project directory and file based variables 00:03
ERROR: Job failed: exit status 1
```

**Comment by muja** [comment]
Please tell me the build does not hard-fail because generated code could not be formatted, i.e. `rustfmt` could not be found.
Please excuse my rant. I just spent an entire day trying to debug the GitLab pipeline (which is extremely frustrating as it is), assuming I was missing a core dependency like webview-runtime or whatever...

Anyway... `rustfmt` should definitely not be a hard dependency at build time, it should be optional at worst (and not used at all, at best -- who cares about formatting on generated files?)

**Comment by wravery** [comment]
> Please tell me the build does not hard-fail because generated code could not be formatted, i.e. `rustfmt` could not be found. Please excuse my rant. I just spent an entire day trying to debug the GitLab pipeline (which is extremely frustrating as it is), assuming I was missing a core dependency like webview-runtime or whatever...

Sorry about that, I've never used GitLab pipelines myself.

> Anyway... `rustfmt` should definitely not be a hard dependency at build time, it should be optional at worst (and not used at all, at best -- who cares about formatting on generated files?)

I haven't figured out a way to build directly from the `OUT_DIR`, so it needs to copy the file back to the source directory. Anything that's committed in the source directory I want to be human readable. This also makes it a lot easier to inspect or debug through the generated code when there's a problem.

I think rather than skipping `rustfmt`, it would be better to just skip regenerating the bindings and use the previously committed version if `rustfmt` is not available.

**Comment by wravery** [comment]
Just occurred to me, maybe I could `include!(...)` the generated file instead. It would make it a little harder to jump to source, and you couldn't review it in a static repo, e.g., on GitHub, but it would make the build more robust.

**Comment by hjmallon** [comment]
Would you prefer to `include()` generated bindings or some other change (or no change)? I am also interested in fixing this, since rustfmt is not included with the Rust standalone installer.

**Comment by wravery** [comment]
I'm still experimenting with this, another option I'm considering is to move all of this logic out of the build script entirely and create a separate `bin` utility that I can run locally only when updating the bindings. That should make the typical build as a dependency much faster, and not require fetching as many dependencies.

**Comment by muja** [comment]
What's wrong with merging this anyhow? It will still try to rustfmt, only not fail the build when it errors. As long as you have rustfmt installed when generating new bindings, everything will work as usual.
You can still think of something more sophisticated / involved, but I doubt it relates to this PR.
