### ISSUE TITLE
How to use the webview2 object in tauri's .with_webview globally?

### ISSUE THREAD

**Issue by 107295472** [wravery/webview2-rs#26]
main_window
                .with_webview(move |_webview| unsafe {
                    let core = _webview.controller().CoreWebView2().unwrap();

core wants to use it in other methods

**Comment by wravery** [comment]
Generally speaking, it's probably safer to call `with_webview` each time. That way you don't have objects living past their owners.

However, `ICoreWebView2` is a ref-counted COM interface under the covers, and the Rust projection should implement the `Clone` trait. If you have mutable access to a global variable, you can theoretically either move `core` into it or assign `core.clone()` to it if you need to keep accessing `core` after the assignment.

**Comment by 107295472** [comment]
Thanks  
Uncaught (in promise) Scope not defined for URL `http://xxxxx/`. See https://tauri.app/v1/api/config/#securityconfig.dangerousremotedomainipcaccess and https://docs.rs/tauri/1/tauri/scope/struct.IpcScope.html#method.configure_remote_access

Please ask the following question, it is also set
 "security": {
      "csp": null,
      "dangerousRemoteDomainIpcAccess": [
        {
          "domain": "ip",
          "windows": [
            "main"
          ],
          "enableTauriAPI": true
        }
      ]
    }
